# general settings
name: Unet_LDCTDenoising_GaussianSigma5
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_CTDenoising
    sigma_type: constant
    sigma_range: 5
    test_patient: L506
    in_ch: 1    ## Single-channel CT image

    dataroot_gt: /home/gabriel/Research/dataset/mayo-challenge/npy_img
    geometric_augs: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16

    mini_batch_sizes: [16]
    iters: [40000]
    gt_size: 128
    gt_sizes: [128]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_CTDenoising
    in_ch: 1  ## Single-channel CT image
    dataroot_gt: /home/gabriel/Research/dataset/mayo-challenge/npy_img
    test_patient: L506


# network structures
network_g:
  type: Unet
  in_channels: 1
  out_channels: 1
  channel: 64
  output_activation: ~  # None for regression (denoising)
  use_batchnorm: true

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 40000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 40000
    eta_min: !!float 1e-6

  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 3e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 32
  val_freq: !!float 4e3
  save_img: false
  rgb2bgr: False
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: compute_PSNR
      data_range: 4096
      trunc_min: -1024
      trunc_max: 3072
      norm_range_min: -1024
      norm_range_max: 3072
    ssim:
      type: compute_SSIM
      data_range: 4096
      trunc_min: -1024
      trunc_max: 3072
      norm_range_min: -1024
      norm_range_max: 3072

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e5
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
